
services:
  frontend-insurecowportal-prod:
    image: insurecow/insurecow_warehouse_repo:frontend-insurecowportal-prod
    container_name: frontend-insurecowportal-prod
    ports:
      - "3012:3000"
    restart: always